name: PR Build & Test - Nextflow-Runner API

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'NextflowRunnerClient/**'
      - 'templates/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    name: Build & Test - NextflowRunner.API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Build API
      run: dotnet build ./NextflowRunner.API --configuration Release

    - name: Build DACPAC
      run: dotnet build ./NextflowRunnerDB.Build --configuration Release

    - name: Build Serverless
      run: dotnet build ./NextflowRunner.Serverless --configuration Release

    - name: Test API
      run: dotnet test ./NextflowRunner.API

    - name: Test Serverless
      run: dotnet test ./NextflowRunner.Serverless
